user  nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    # Frontend
    server {
        listen 80;
        server_name vivekbackend.duckdns.org;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;  # SPA support
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend-blue:8000;   # Forward /api to backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
