worker_processes 1;

events { worker_connections 1024; }

http {
    upstream backend_active {
        server backend-blue:8000;
        # server backend-green:8000; # switch when green is active
    }

    server {
        listen 80;
        server_name vivekbackend.duckdns.org;

        location / {
            proxy_pass http://fullstack-project-frontend-1:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend_active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        error_page 502 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
